GET http://localhost:3001/api/notes/




###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": false
}

###
GET http://localhost:3001/api/notes/someid


###
DELETE http://localhost:3001/api/notes/6112a98b5315010015aab726