GET http://localhost:3001/api/notes/




###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": false
}

###
GET http://localhost:3001/api/notes/someid


###
DELETE http://localhost:3001/api/notes/610919c9b4a8361fae7cf7f5
